### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SqltyNate** [SuperRonanCraft/AdvancedCustomMenu#14]
Suggestion:
  - Command delays. E.g If I wanted to make a countdown, I could add a delay between each 

broadcast. E.g, 
Commands:
- 'broadcast: 10 seconds left'
Delay: 5secs
- 'broadcast: 5 seconds left'
Delay: 1sec
- 'broadcast: 4 seconds left'
etc.

**Comment by SuperRonanCraft** [comment]
I will definitely love to add this, thinking about having these as a command type, so it waits before the next command is executed instead of just forcing all commands

**Comment by SqltyNate** [comment]
Sure, also, could you add a Per-World setting to add to a config? (Preferably to work with Multiverse-Core)
:)

**Comment by SuperRonanCraft** [comment]
That might be part of the actual menu, cause I want the config to be like global settings, even though worlds are *kinda* global, it just makes more sense to put it in each menu :P

**Comment by Andre601** [comment]
You could add something similar like the prefixes, to tell ACM, to send a message, instead of running a command...
What I mean is, that you could make, that it will look for integers and run the command after the given interval.

**Example:**
```yaml
Click-Handlers:
  1:
    Commands:
    - 'say I will run instant!'
    - '20: say 1 second later...' # 20 is the time in ticks
    - '40: say 2 seconds later...'
    - '60: say 3 seconds later...'
```
Th only question would be, how to use other functions like sending a message (message:) or sending the player to another server (server:) when you already use a prefix for the delay...

**Comment by SqltyNate** [comment]
Instead of "say 1 second later..." couldn't I put broadcast?

**Comment by Andre601** [comment]
That was a example.....

**Comment by SuperRonanCraft** [comment]
Finally added support for delays between a command executing, all commands will be executed at the same time, in chronological order by default, but if you add "{delay:<ticks>}" you can delay just that one command by how much you like. I will be adding support for extended delays, such like if you wanted to make this plugin remove a permission later in time, the delays will be saved to a file, much like command delays do.
Here's an example of this is action:
```yaml
Commands:
- 'message: You will be warped to spawn in 5 seconds!'
- 'player: warp spawn {delay:100}'
- 'message: You''ve been warped to spawn! {delay:110}'
```
