### ISSUE TITLE
How can I open another menu ?

### ISSUE THREAD

**Issue by TheIntelloBox** [SuperRonanCraft/AdvancedCustomMenu#24]
Hey,

I created the menu "Example", and the menu "MobArena". How can I open the menu MobArena by clicking on a skull in the menu Example ?

Thanks !

**Comment by Andre601** [comment]
Add a click-handler to the item like that:
```yaml
    Click-Handlers:
      1:
        Commands:
        - 'menu: mobarena' #Name of the yml-file without .yml
```
